on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: 3b297dc3c829432eb69b05d6db10959e.azurecr.io
        username: ${{ secrets.acr_3b297dc3c829432eb69b05d6db10959e_username }}
        password: ${{ secrets.acr_3b297dc3c829432eb69b05d6db10959e_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Microsoft" -f  "pp" -t 3b297dc3c829432eb69b05d6db10959e.azurecr.io/azookubectl:${{ github.sha }} --label dockerfile-path=pp
        docker push 3b297dc3c829432eb69b05d6db10959e.azurecr.io/azookubectl:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_azookubectl_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep azookubectlb86b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace azookubectlb86b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: azookubectlb86b
        container-registry-url: 3b297dc3c829432eb69b05d6db10959e.azurecr.io
        container-registry-username: ${{ secrets.acr_3b297dc3c829432eb69b05d6db10959e_username }}
        container-registry-password: ${{ secrets.acr_3b297dc3c829432eb69b05d6db10959e_password }}
        secret-name: azookubectldockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: azookubectlb86b
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          3b297dc3c829432eb69b05d6db10959e.azurecr.io/azookubectl:${{ github.sha }}
        imagepullsecrets: |
          azookubectldockerauth
